### ISSUE TITLE
RedisStreamPublisher nem veszi figyelembe a producer config-ot

### ISSUE THREAD

**Issue by martin-nagy** [i-Cell-Mobilsoft-Open-Source/coffee#306]
Hiábba állítjuk be a producer config-ot, a RedisStreamPublisher nem használja fel. Pl:
```yml
coffee:
  redisstream:
    example:
      producer:
        ttl: 3600000
```
